require "faraday"
require "json"
require "twitch/version"

module Twitch
  autoload :Error, "twitch/error"
  autoload :UnsafeRequestPathError, "twitch/error"
  autoload :Errors, "twitch/error_generator"
  autoload :ErrorGenerator, "twitch/error_generator"
  autoload :ErrorFactory, "twitch/error_generator"

  autoload :RateLimiter, "twitch/rate_limiter"

  autoload :Client, "twitch/client"
  autoload :Collection, "twitch/collection"
  autoload :Resource, "twitch/resource"
  autoload :Object, "twitch/object"

  autoload :OAuth, "twitch/oauth"
  autoload :EventsubWebhook, "twitch/eventsub_webhook"


  autoload :UsersResource, "twitch/resources/users"
  autoload :ChannelsResource, "twitch/resources/channels"
  autoload :EmotesResource, "twitch/resources/emotes"
  autoload :BadgesResource, "twitch/resources/badges"
  autoload :GamesResource, "twitch/resources/games"
  autoload :VideosResource, "twitch/resources/videos"
  autoload :ClipsResource, "twitch/resources/clips"
  autoload :EventsubSubscriptionsResource, "twitch/resources/eventsub_subscriptions"
  autoload :EventsubConduitsResource, "twitch/resources/eventsub_conduits"
  autoload :BannedUsersResource, "twitch/resources/banned_users"
  autoload :ModeratorsResource, "twitch/resources/moderators"
  autoload :PollsResource, "twitch/resources/polls"
  autoload :PredictionsResource, "twitch/resources/predictions"
  autoload :StreamScheduleResource, "twitch/resources/stream_schedule"
  autoload :SearchResource, "twitch/resources/search"
  autoload :StreamsResource, "twitch/resources/streams"
  autoload :StreamMarkersResource, "twitch/resources/stream_markers"
  autoload :SubscriptionsResource, "twitch/resources/subscriptions"
  autoload :CustomRewardsResource, "twitch/resources/custom_rewards"
  autoload :CustomRewardRedemptionsResource, "twitch/resources/custom_reward_redemptions"
  autoload :CustomPowerUpsResource, "twitch/resources/custom_power_ups"
  autoload :GoalsResource, "twitch/resources/goals"
  autoload :HypeTrainStatusResource, "twitch/resources/hype_train_status"
  autoload :AnnouncementsResource, "twitch/resources/announcements"
  autoload :RaidsResource, "twitch/resources/raids"
  autoload :ChatMessagesResource, "twitch/resources/chat_messages"
  autoload :PinnedChatMessagesResource, "twitch/resources/pinned_chat_messages"
  autoload :VipsResource, "twitch/resources/vips"
  autoload :WhispersResource, "twitch/resources/whispers"
  autoload :AutomodResource, "twitch/resources/automod"
  autoload :BlockedTermsResource, "twitch/resources/blocked_terms"
  autoload :CharityCampaignsResource, "twitch/resources/charity_campaigns"
  autoload :ChattersResource, "twitch/resources/chatters"
  autoload :ShoutoutsResource, "twitch/resources/shoutouts"
  autoload :SharedChatSessionsResource, "twitch/resources/shared_chat_sessions"
  autoload :UnbanRequestsResource, "twitch/resources/unban_requests"
  autoload :WarningsResource, "twitch/resources/warnings"
  autoload :SuspiciousUsersResource, "twitch/resources/suspicious_users"
  autoload :AdsResource, "twitch/resources/ads"
  autoload :AnalyticsResource, "twitch/resources/analytics"
  autoload :BitsResource, "twitch/resources/bits"
  autoload :ChatSettingsResource, "twitch/resources/chat_settings"
  autoload :ContentClassificationLabelsResource, "twitch/resources/content_classification_labels"
  autoload :DropsEntitlementsResource, "twitch/resources/drops_entitlements"
  autoload :ExtensionsResource, "twitch/resources/extensions"
  autoload :GuestStarResource, "twitch/resources/guest_star"
  autoload :ShieldModeResource, "twitch/resources/shield_mode"
  autoload :TeamsResource, "twitch/resources/teams"


  autoload :User, "twitch/objects/user"
  autoload :BlockedUser, "twitch/objects/blocked_user"
  autoload :StreamKey, "twitch/objects/stream_key"

  autoload :Channel, "twitch/objects/channel"
  autoload :ChannelEditor, "twitch/objects/channel_editor"
  autoload :Emote, "twitch/objects/emote"
  autoload :Badge, "twitch/objects/badge"
  autoload :Game, "twitch/objects/game"
  autoload :Video, "twitch/objects/video"
  autoload :Clip, "twitch/objects/clip"
  autoload :ClipDownload, "twitch/objects/clip_download"
  autoload :EventsubSubscription, "twitch/objects/eventsub_subscription"
  autoload :EventsubConduit, "twitch/objects/eventsub_conduit"
  autoload :EventsubConduitShard, "twitch/objects/eventsub_conduit_shard"
  autoload :BannedUser, "twitch/objects/banned_user"
  autoload :Moderator, "twitch/objects/moderator"
  autoload :Poll, "twitch/objects/poll"
  autoload :Prediction, "twitch/objects/prediction"
  autoload :StreamSchedule, "twitch/objects/stream_schedule"
  autoload :SearchResult, "twitch/objects/search_result"
  autoload :Stream, "twitch/objects/stream"
  autoload :StreamMarker, "twitch/objects/stream_marker"
  autoload :Subscription, "twitch/objects/subscription"
  autoload :SubscriptionCount, "twitch/objects/subscription_count"
  autoload :CustomReward, "twitch/objects/custom_reward"
  autoload :CustomRewardRedemption, "twitch/objects/custom_reward_redemption"
  autoload :CustomPowerUp, "twitch/objects/custom_power_up"
  autoload :Goal, "twitch/objects/goal"
  autoload :HypeTrainStatus, "twitch/objects/hype_train_status"
  autoload :FollowCount, "twitch/objects/follow_count"
  autoload :Raid, "twitch/objects/raid"
  autoload :UserColor, "twitch/objects/user_color"
  autoload :Vip, "twitch/objects/vip"
  autoload :AutomodStatus, "twitch/objects/automod_status"
  autoload :AutomodSetting, "twitch/objects/automod_setting"
  autoload :BlockedTerm, "twitch/objects/blocked_term"
  autoload :CharityCampaign, "twitch/objects/charity_campaign"
  autoload :Chatter, "twitch/objects/chatter"
  autoload :ChatMessage, "twitch/objects/chat_message"
  autoload :PinnedChatMessage, "twitch/objects/pinned_chat_message"
  autoload :SharedChatSession, "twitch/objects/shared_chat_session"
  autoload :UnbanRequest, "twitch/objects/unban_request"
  autoload :Warning, "twitch/objects/warning"
  autoload :SuspiciousUser, "twitch/objects/suspicious_user"
  autoload :UserAuthorization, "twitch/objects/user_authorization"
  autoload :AdSchedule, "twitch/objects/ad_schedule"
  autoload :AnalyticsReport, "twitch/objects/analytics_report"
  autoload :BitsLeaderboardEntry, "twitch/objects/bits_leaderboard_entry"
  autoload :Cheermote, "twitch/objects/cheermote"
  autoload :CharityDonation, "twitch/objects/charity_donation"
  autoload :ChatSettings, "twitch/objects/chat_settings"
  autoload :ContentClassificationLabel, "twitch/objects/content_classification_label"
  autoload :DropsEntitlement, "twitch/objects/drops_entitlement"
  autoload :DropsEntitlementUpdate, "twitch/objects/drops_entitlement_update"
  autoload :ShieldModeStatus, "twitch/objects/shield_mode_status"
  autoload :Team, "twitch/objects/team"
  autoload :UserExtension, "twitch/objects/user_extension"
  autoload :UserActiveExtensions, "twitch/objects/user_active_extensions"
  autoload :Extension, "twitch/objects/extension"
  autoload :ExtensionLiveChannel, "twitch/objects/extension_live_channel"
  autoload :ExtensionConfigurationSegment, "twitch/objects/extension_configuration_segment"
  autoload :ExtensionSecret, "twitch/objects/extension_secret"
  autoload :ExtensionBitsProduct, "twitch/objects/extension_bits_product"
  autoload :ExtensionTransaction, "twitch/objects/extension_transaction"
  autoload :GuestStarSettings, "twitch/objects/guest_star_settings"
  autoload :GuestStarSession, "twitch/objects/guest_star_session"
  autoload :GuestStarInvite, "twitch/objects/guest_star_invite"
end
